[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.6"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
